---
- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-pip
      - python3-docker
    state: present
    update_cache: yes

- name: Start and enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Allow deploy user to run Docker commands
  ansible.builtin.user:
    name: "{{ app_user }}"
    groups: docker
    append: yes
